server:
  port: ${SERVER_PORT}

spring:
  application:
    name: loan-flow

  # DATABASE CONNECTION (PostgreSQL)
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA / HIBERNATE CONFIGURATION
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
